from telegram import KeyboardButton

# Стан розмови
START, NAME, AGE, CITY, LOCATION, GENDER, SEARCH, CONFIRMATION, VIEW_PROFILES, SEARCH_PROFILES, PREMIUM, SUBSCRIPTION, GIFT, ENTER_KEY, AGE_RANGE, MAX_AGE, ADULT_NAME, ADULT_AGE, ADULT_CITY, ADULT_LOCATION, ADULT_GENDER, ADULT_SEARCH, ADULT_CONFIRMATION, ADULT_VIEW_PROFILES, HOBBY, PHOTO = range(26)

PREMIUM_STICKER_ID = "CAACAgUAAxkBAAIKkWZ13fvfJF-qwg3ix6yvNxd7WERpAAKmAwAC6QrIA3mzkAhrhbH0NQQ"
LOVE_STICKER_ID = "CAACAgIAAxkBAAIKk2Z13glz9gcAATCnSDS6Jpq-lM0BhAACiQIAAladvQqhVs0CITIOPTUE"

MAIN_MENU_BUTTONS = [
    [KeyboardButton("Знайомства")],
    [KeyboardButton("18+")],
    [KeyboardButton("Ввести унікальний ключ")]
]
